per_page: 10
per_page_admin: 5
User:
  name_length_max: 50
  email_length_max: 255
  phone_length_max: 13
  phone_length_min: 9
  address_length_min: 5
  password_length_min: 6
  is_remember_pass: "1"
max_size_img: 5
tour:
  address_length_max: 200
category:
  address_length_max: 200
stt: 0
